baseurl = "https://du1ab.one/"
languageCode = "zh-cn"
title = "Wuan's Blog"
theme = "ezhil"
paginate = 5
copyright = "Copyleft 🄯 2006-2021"

disqusShortname = "s5unty"
summaryLength = 30
enableEmoji = true

[markup]
  [markup.highlight]
    # 内置的 chroma 高亮，对 asciidoc 支持不好
    # 明确禁用，避免和 highlight.js 重复高亮
    codeFences = false

[params]
	subtitle = "拉出去就地正法久住"
	disableDisqusTypes = ["page"]
	featherIconsCDN = true
	mode = "auto" # "dark", "auto", "light"
 	customCSS = ["css/fonts.css", "css/github.min.css"]  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	customJS = ["js/highlight.min.js"]  # Custom JS scripts.

[[menu.main]]
name = "Root"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/s5unty"

[[params.social]]
name = "Theravada"
icon = "settings"
url = "https://www.notion.so/s5unty/3305c2f6ac824ba78df2dd6c278e1c8a"

[taxonomies]
   tag = "tags"
